### ISSUE TITLE
Archive shows from last night showing error message (older than 2 weeks)

### ISSUE THREAD

**Issue by Pammeke** [WMFO/wiki#2]
My show (On the Town with Mikey Dee, hosted by Pammeke) from last night is not loading with an archive (the playlist loads fine), and I get the following error message when I try to access it (same with other shows I've tested from yesterday):

Oh No!
The DMCA has imposed a two week limit on your archive-listening pleasure. Boo!
Want to see things change? Check out the following resources:
– askcbi.com
– freeradioalliance.org
– nab.org
<< back
Comments are closed.

**Comment by nickandre** [comment]
The program logic was a little worse for the wear but I've updated it so hopefully we should be AOK.

Please confirm that this is fixed and then I can close it.

**Comment by Pammeke** [comment]
Nick, you are a king among men. Thank you!! Fixed. Huzzah.
